지원서 등록 API 구현
miracle-job-a/user-service pull request #37
Opened 2023-11-30 12:22 UTC by hazzokko

2023-11-30 18:24 UTC, chocolaggibbiddori requested changes
충돌 해결도 하면서 리뷰 확인해주세요~~

2023-11-30 18:24 UTC, chocolaggibbiddori commented on src/main/java/com/miracle/userservice/dto/request/ApplicationLetterPostRequestDto.java
> +    }
사용되지 않는 생성자 매개변수가 왜 이렇게 많은가요

2023-11-30 18:24 UTC, chocolaggibbiddori commented on src/main/java/com/miracle/userservice/service/ApplicationLetterService.java
> +    boolean postApplicationLetter(Long userId, Long resumeId, Long coverLetterId, ApplicationLetterPostRequestDto dto);
주석에 NullPointerException은 한 줄로 써줘도 되겠다는?
`@throws NullPointerException If either parameters is null`

2023-11-30 18:24 UTC, chocolaggibbiddori commented on src/main/java/com/miracle/userservice/service/ApplicationLetterServiceImpl.java
> +    }
이력서와 자기소개서가 존재하지 않을 경우 각각 400_1, 400_2 에러 코드를 발생시키는데, 해당 에러 코드는 RequestBody 검증에 이미 있지 않나요? 400_5까지 있었던거 같음

2023-12-01 05:29 UTC, hazzokko commented on src/main/java/com/miracle/userservice/dto/request/ApplicationLetterPostRequestDto.java
> +    private final PostType postType;
수정 완료!

2023-12-01 06:06 UTC, hazzokko commented on src/main/java/com/miracle/userservice/controller/ApplicationLetterController.java
> +    }
@PathVariable 로 받는게 나을까 싶어서 뺐다가 바꿨는데 하하 dto 추가로 수정

2023-12-01 06:10 UTC, hazzokko commented on src/main/java/com/miracle/userservice/service/ApplicationLetterServiceImpl.java
> +    }
ValidationDefaultMsgUtil 수정 완료!

2023-12-01 06:38 UTC, hazzokko commented on src/main/java/com/miracle/userservice/dto/request/ApplicationLetterPostRequestDto.java
> +    }
삭제 완료

2023-12-01 16:10 UTC, chocolaggibbiddori commented on src/main/java/com/miracle/userservice/dto/request/ApplicationLetterPostRequestDto.java
>      private final LocalDateTime submitDate;
참고로 말씀드리면 시간은 보통 소문자로 표기합니당 hh

저 형식으로 요청하면 `LocalDateTime`으로 잘 변환되던가요?

2023-12-01 16:14 UTC, chocolaggibbiddori approved these changes

2023-12-03 08:02 UTC, merged